### ISSUE TITLE
Quienes somos 

### ISSUE THREAD

**Issue by palolo25** [G5-Squad-Edix/aristopets#12]
# Quienes somos
### **Contexto**
En esta parte de la pagina se desarrolla el origen de la misma, en este apartado se tiene que ver reflejado quienes somos los integrantes, donde desarrollamos la actividad y como lo hacemos, desde cuando nos dedicamos a esta actividad y mostrar resultados obtenidos por la organizacion.

- Quienes somos.
En este apartado nombrar a todo el equipo con una historia(inventada) sobre quienes somos.

- Donde se desrrolla nuestro trabajo.
Establecer un lugar fisico dentro de territorio español donde aristopets desarrolla su trabajo.

- En que consiste nuestro trabajo.
En este punto informar sobre como realizamos el trabajo en relacion a las adopciones, acogidas y voluntariado.

- Desde hace cuanto nos dedicamos a este trabajo.
En este punto ocntar que experiencia tenemos dentro de este sector.

- Resultados de Aristopets
Aqui enseñar que resultados ha obtenido la organizacion, para asi poder darles esa confianza de que en Aristopets se obtienen resultados satifactorios.

## En esta sección se deberá presentar a la organización:
1. Objetivos
1. Historia
1. Principios
1. Organigrama
1. Lista de centros
## Cada ficha de centro deberá contener:
1. Nombre de la sede
1. Descripción resumen (300 caracteres)
1. Dirección
1. Datos de contacto
1. Mapa
1. Enlace a la página detalle del centro
# **Tareas**
- [ ] Quienes son los integrantes
- [ ] Donde se desarrolla nuestro trabajo
- [ ] En que consiste nuestro trabajo
- [ ] Desde hace cuanto que nos dedicamos este trabajo
- [ ] Resultados obtenidos por Aristopets

**Comment by aseguragonzalez** [comment]
@G5-Squad-Edix/g5team  creo que del acta de reunión del día [09/04/2022](https://github.com/G5-Squad-Edix/aristopets/issues/2#issuecomment-1094106350) falta meter en esta sección:

- Organigrama
- Lista de centros (lista de fichas de cada centro)

Cada ficha de centro deberá contener:
- Nombre de la sede
- Descripción resumen (300 caracteres)
- Dirección
- Datos de contacto
- Mapa (localización del centro)
- Enlace a la página detalle del centro

Esto incluye también una página detalle del centro en particular.

**Comment by palolo25** [comment]
gracias @aseguragonzalez he añadido lo que faltaba a la issue para que este completa con lo hablado

**Comment by palolo25** [comment]
![Apartado de quienes somos4](https://user-images.githubusercontent.com/89455065/162803853-dce7693a-317e-47ff-a669-3dbe1799b7c2.png)
