### ISSUE TITLE
Elección de logos

### ISSUE THREAD

**Issue by tiznajo** [G5-Squad-Edix/aristopets#5]
# Elección de logo

## Requisitos previos

N/A.

## Contexto

Necesitamos escoger el logo que utilizaremos para dar imagen a la protectora.
## Criterios de aceptación

Para completar la tarea debemos escoger un logo final.

## Tareas

- [x] Votar sobre el diseño más adecuado.

## Logo 1
![Logo 1](https://user-images.githubusercontent.com/98710228/162578468-53d42480-5a7f-4c3a-994b-6f0d38a660d2.png)
## Logo 2
![Logo 2](https://user-images.githubusercontent.com/98710228/162578475-40c8337d-7d17-434c-a1dc-124f835e3340.png)
## Logo 3
![Logo 3](https://user-images.githubusercontent.com/98710228/162578473-4b8fcd7a-fc5a-45cd-b248-267059a90f41.png)
## Logo 4
![Logo 4](https://user-images.githubusercontent.com/98710228/162578469-002bbcd6-d386-48ff-a75c-33f327b5e071.png)

**Comment by mncaseny** [comment]
Hola,
muchas gracias Santi.
la verdad es que todos los logos me gustan. Quizá me decantaría por el segundo o el cuarto logo.
¿Qué opináis?

**Comment by mncaseny** [comment]
Me decantaría por los logos 2 y 4.

**Comment by palolo25** [comment]
Me uqedo con el logo 4 es mas chulo

**Comment by aseguragonzalez** [comment]
Creo que estoy entre el logo 1 y el 3. Creo que pueden quedar bien como favico, son sencillos y entiendo que fáciles para vectorizar.

**Comment by aseguragonzalez** [comment]
Tras la votación, el logo seleccionado es el 1:

![162578468-53d42480-5a7f-4c3a-994b-6f0d38a660d2](https://user-images.githubusercontent.com/2671340/164889969-803bc3c0-a6d9-43f6-9421-0dc3ebd19d86.png)
